// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrlIYJy2FU7kEQWnZFZA5i7apHmn64vk',
    appId: '1:153175417813:web:626541f04567afb1e6d35c',
    messagingSenderId: '153175417813',
    projectId: 'diaree-4f926',
    authDomain: 'diaree-4f926.firebaseapp.com',
    storageBucket: 'diaree-4f926.appspot.com',
    measurementId: 'G-S0FBVSELDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYv3LC7g0yVvd8e5Ph0aE8gbW2Pzn2nM',
    appId: '1:153175417813:android:43f6fcbb735a5d22e6d35c',
    messagingSenderId: '153175417813',
    projectId: 'diaree-4f926',
    storageBucket: 'diaree-4f926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdI-wG97OiVHS60fVGvA7rwusJ3zUdnk',
    appId: '1:153175417813:ios:79e9de49c383fa5ce6d35c',
    messagingSenderId: '153175417813',
    projectId: 'diaree-4f926',
    storageBucket: 'diaree-4f926.appspot.com',
    androidClientId: '153175417813-jft7s3mjg8uppar7rjjg7o67jeqm55eo.apps.googleusercontent.com',
    iosClientId: '153175417813-4e7ubi0g6fae5euoujgkau3c9bsor5au.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaree',
  );
}
